AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Sample SAM Template for c-sharp

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: c-sharp-function1-sam-test
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Function
      CodeUri: src/Function/
      Handler: Function::Function::Handler 
      Runtime: dotnet8
      MemorySize: 3008
      Timeout: 60
      Tracing: Active
      Role: arn:aws:iam::933489381270:role/AWSNetworkLambdaServiceRole
      VpcConfig:
        SecurityGroupIds:
          - sg-01979a55a831a51ac
        SubnetIds:
          - subnet-06d47cc103b00d8df
          - subnet-0e06d2b7a43c2f810
      Environment:
        Variables:
          database: "LoanDQ"
          password: "ZGY5Nzg0MDg3YWN"
          server: "ptc-wbafgdb312.ad.moodys.net"
          userid: "loandq_user"
          s3_bucket_name: "aws-lambda-functions-bucket-excel"
  
  