AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Sample SAM Template for python

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: python-function-1
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: Function
      CodeUri: src/Function
      Handler: handler.handler
      Runtime: python3.11
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Role: arn:aws:iam::933489381270:role/AWSNetworkLambdaServiceRole
      VpcConfig:
        SecurityGroupIds:
          - sg-01979a55a831a51ac
        SubnetIds:
          - subnet-06d47cc103b00d8df
          - subnet-0e06d2b7a43c2f810 
      Layers: 
          - arn:aws:lambda:us-east-1:933489381270:layer:pyodbc_layer:7
          - arn:aws:lambda:us-east-1:933489381270:layer:openpyxl-layer:1
      Environment:
        Variables:
          DB_NAME: "LoanDQ"
          DB_PASSWORD: "ZGY5Nzg0MDg3YWN"
          DB_SERVER: "ptc-wbafgdb312"
          DB_USER: "loandq_user"
          s3_bucket_name: "aws-lambda-functions-bucket-excel"
  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Function}
  