name: Deploy SAM Application to AWS

# Trigger the workflow on push to main or any changes in the specified branch
on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Set up Python environment (if required)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Change if you're using another version of Python

    # Step 5: Install SAM CLI
    - name: Install AWS SAM CLI
      run: |
        curl -Lo sam-cli-linux-x86_64.tar.gz https://github.com/aws/aws-sam-cli/releases/download/v1.34.0/aws-sam-cli-linux-x86_64.tar.gz
        sudo tar -xvzf sam-cli-linux-x86_64.tar.gz -C /usr/local/aws-sam-cli
        sudo ln -s /usr/local/aws-sam-cli/aws-sam-cli /usr/local/bin/sam

    # Step 6: Build the SAM application
    - name: Build SAM application
      run: sam build
