name: Deploy SAM Application to AWS

# Trigger the workflow on push to main or any changes in the specified branch
on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Set up Python environment (if required)
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Change if you're using another version of Python

    - name: Set up AWS SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    # Step 5: Build Python functions
    - name: Build Python functions
      run: |
        cd lambda-functions/python
        sam build --use-container

    # Step 6: Build C# functions
    - name: Build C# functions
      run: |
        cd lambda-functions/csharp
        sam build

    # Step 7: Build Node.js functions
    - name: Build Node.js functions
      run: |
        cd lambda-functions/nodejs
        sam build
